### ISSUE TITLE
enableSeveralDrivers="true"

### ISSUE THREAD

**Issue by alpha117** [yumi-modding/FS17_ContractorMod#10]
This gives very strange results if you put two contractors in the same cab.
Then one gets out, they both get out but leaves a 'no name' person in the cab

**Comment by yumi-modding** [comment]
Hello,
Thx for the report.
Yes this is something that I've not really tested.
FYI, the goal was to be able to drive several characters to a given place for vehicle/mods that don't have Passenger specialization without using "Jump to vehicle" capability.
The thing is now Passenger spec on FS17 is not working anymore from I what tested and so I should work on this and maybe try also to benefit from Passenger stuff in xml for mods to display several .
I kind of already logged the issue in #2

**Comment by alpha117** [comment]
Thanks

Hopefully you can get it sorted

**Comment by massyas** [comment]
Cf. passenger_support branch that activates passenger with visual.
To be merged in main branch when fully tested.

**Comment by yumi-modding** [comment]
Cf. passenger_support branch that activates passenger with visual.
To be merged in main branch when fully tested.

**Comment by yumi-modding** [comment]
Fixed by https://github.com/yumi-modding/FS17_ContractorMod/commit/40db0b59f04793eba81d846203f963963ab4ed95
