### ISSUE TITLE
Conflict with Farming Tablet.

### ISSUE THREAD

**Issue by PhilBrownFarming** [yumi-modding/FS17_ContractorMod#29]
Since the update to correct the leaning player, the mod has a conflict with the Farming Tablet mod. It causes the notification text on the farming tablet to move left from the background grey box. I use 3440x1440 resolution. The text returns to normal if the mod is removed.

**Comment by yumi-modding** [comment]
Thanks for raising this issue here. I will reproduce the issue (I'm not using Farming Tablet mod right now) and propose a fix for next update.

**Comment by yumi-modding** [comment]
Hello,
I'm not able to reproduce this issue.
I don't have screen that supports this resolution so I tested on 2736x1824
Do you have Ingame HUD scale different than 100% ?
Could you please share a screenshot ?
Could you please test only with FarmingTablet mod + ContractorMod and then only FarmingTablet mod to confirm conflict is with ContractorMod ?
I really doubt last fix could impact this.
Thanks

**Comment by PhilBrownFarming** [comment]
Hi, I have tested again with farming Tablet and apps with the contractor mod and can confirm I can reproduce this error 100%. It goes away with the contractor mod removed. I do use hud scale of 50%, but have tried it at 100% and it still happens. 
I needed a mod map as Vanilla maps have no scripts to trigger any notifications. I normally use Hof Bergmann 1.0.0.7. but to double check I loaded a new game with Pacific Northwest.
Screenshot. 
![fsscreen_2018_07_19_19_38_41](https://user-images.githubusercontent.com/41343240/42963660-c6b9a870-8b8c-11e8-9365-75bab02fedb2.png)

I love the mod. My only request is a way to disable the passenger seat, as I get lots of errors in the log related to the seat not being defined. As I normally use lots of mods, it is not really an option to work out the position for each one. Thanks for looking into this for me.

**Comment by yumi-modding** [comment]
Thanks for these details. It will really help to fix the issue.
I'll add a variable to disable warning in logs. It can help to identify the mods not configured yet for passengers but of course if you have a lot of mods it will be very verbose.
