### ISSUE TITLE
Entering Train not supported

### ISSUE THREAD

**Issue by dolfin2** [yumi-modding/FS17_ContractorMod#31]
When entering the train (\vehicles\train\locomotive.xml) the game freezes. The console prints the error

Error: Running LUA method 'update'.
d:/Users/Michael/Documents/My Games/FarmingSimulator2017/mods/FS17_ContractorMod/scripts/ContractorMod.lua:551: attempt to index field 'passengers' (a nil value)

Passenger seats for the train need to be defined

**Comment by yumi-modding** [comment]
Hello,
Thanks for this issue. I've not tested this scenario.
I will reproduce it and provide a fix asap.
Yumi
