### ISSUE TITLE
critical camera failure with the lumber yard crane

### ISSUE THREAD

**Issue by Dudejo** [yumi-modding/FS17_ContractorMod#36]
https://cdn.discordapp.com/attachments/412348931473801217/492051167577112591/fsScreen_2018_09_19_15_14_44.png

https://cdn.discordapp.com/attachments/412348931473801217/492051147885117453/fsScreen_2018_09_19_15_15_15.png

When I enter the crane with any character, the camera breaks completely and it becomes impossible to recover.

The log returns an error relating to the passenger script, iirc

**Comment by yumi-modding** [comment]
Hello,
Thanks for your report. I had to test this but I forgot. I'll see how to fix the issue.
