### ISSUE TITLE
Customizing a vehicle turns the vehicle to an object and is gone after restart.

### ISSUE THREAD

**Issue by asyvan** [yumi-modding/FS17_ContractorMod#57]
Customizing a vehicle turns the vehicle to an object and is gone after restart.
For example chaning tires, or engine configuration, the vehicle (tractor) is turned to an object (you can see if since the "hand" for grabbing an object is visible when you try to enter it (you obviously can't). If restarting, the vehicle is gone, removed from the save game.
This happens on standard map with no other mods loaded.

**Comment by yumi-modding** [comment]
Hello,
Thanks for the issue. I've already seen it during tests but it was supposed to be fixed. I will check if I can reproduce it.

**Comment by yumi-modding** [comment]
I confirm the bug and this is a regression introduced very recently. I'll make a fix asap. Thanks again for taking the time to report it.

**Comment by asyvan** [comment]
np. Love the mod. Good work.

There is some comments on the mod here:
https://forum.giants-software.com/viewtopic.php?f=963&t=141468&start=15

**Comment by yumi-modding** [comment]
Issue comes from https://github.com/yumi-modding/FS17_ContractorMod/blob/e8f50192ba9a835e26388e5af7e0ef6c630a6171/scripts/ContractorMod.lua#L1179
We should call this on Enterable:onLoad(savegame)

**Comment by yumi-modding** [comment]
@asyvan Hello, Please try the last zip (version 1.0.0.2) that should fix the issue. Thanks

**Comment by asyvan** [comment]
Thanks. Works fine. But the file FS19_ContractorMod.zip as seen under "Code" here on GitHub is broken (79kB). I had to Download the entire project and extract it. In there the FS19_ContractorMod.zip file was fine.

**Comment by yumi-modding** [comment]
Thanks. I don't see the file broken here...
I've played several hours with this version and now it's fine for me.
I'll push it to modhub
