### ISSUE TITLE
Problem with Resetting Vehicles/LUA Errors in Log

### ISSUE THREAD

**Issue by cwattyeso** [yumi-modding/FS17_ContractorMod#58]
Hey, sorry to report another bug/glitch that I have encountered today using the Contractor Mod. I had a situation where a vehicle became stuck on the map border, so tried to reset it to the store spawn point. When I selected reset from the main menu the game kept telling me there was not enough space at the store. When I went to check I found this issue;
![2019-05-24](https://user-images.githubusercontent.com/13921716/58324756-ad69f880-7e1f-11e9-937d-4a6612e74920.png)
It seems to spawn a fake vehicle each time you select the reset on the original one. These vehicles can't be entered and obviously clutter up the area.

I also noticed in the console a lua error being generated when trying to reset the vehicle. Here is my log.txt for you to take a log at.
[log.txt](https://github.com/yumi-modding/FS17_ContractorMod/files/3216650/log.txt)

**Comment by yumi-modding** [comment]
Thanks for reporting this issue. Looks like a scenario I've not tested. Should be easy to fix.

**Comment by yumi-modding** [comment]
Issue is actually already fixed by 0a36dfbb6f4d21bc1d361325358295717d682c14 on version 1.0.0.2
