### ISSUE TITLE
Display Settings Changes only Work One Time

### ISSUE THREAD

**Issue by cwattyeso** [yumi-modding/FS17_ContractorMod#59]
Another little bit of a glitch I have found is that if you edit the ContractorMod.xml in the modsettings folder to change the Display Settings for the Position and Size of a characters name it works the first time you load up a game or map with the mod enabled, but after saving and exiting the game the Display Settings revert back to the original values found in the main ContractorMod.xml of the mods zip file.

I've found the only way to ensure the Display Setting information is re-used each time you load up the saved game is to add that line of code from the ContractorMod.xml into the one generated and stored within the actual save game folder. This means on every savegame you have to remember to edit that file once to paste in the code you want e.g.

`<ContractorMod>
    <workers numWorkers="5" enableSeveralDrivers="true" displayOnFootWorker="true">
        <worker name="CWATTYESO" gender="male" playerColorIndex="15" playerBodyIndex="1" playerHatIndex="0" playerAccessoryIndex="1" playerHairIndex="3" playerJacketIndex="1" position="-52.49634552002 32.246616363525 142.94073486328" rotation="-0.96189260482788 0.0023396173492074 0.27341768145561" vehicleID="0"/>
        <worker name="Delores" gender="female" playerColorIndex="13" playerBodyIndex="1" playerHatIndex="0" playerAccessoryIndex="0" playerHairIndex="1" playerJacketIndex="0" currentSeat="0" position="-264.72866821289 33.119937896729 325.05987548828" rotation="0.45028531551361 0.040762983262539 0.89195370674133" vehicleID="1"/>
        <worker name="Chuck" gender="male" playerColorIndex="5" playerBodyIndex="3" playerHatIndex="0" playerAccessoryIndex="0" playerHairIndex="4" playerJacketIndex="0" currentSeat="0" position="-184.81109619141 34.024341583252 333.79852294922" rotation="0.36441880464554 0.032333925366402 0.9306737780571" vehicleID="10"/>
        <worker name="Rose" gender="female" playerColorIndex="16" playerBodyIndex="2" playerHatIndex="0" playerAccessoryIndex="0" playerHairIndex="3" playerJacketIndex="0" currentSeat="0" position="301.87173461914 32.466529846191 143.2698059082" rotation="0.17796717584133 0.063132636249065 0.98200899362564" vehicleID="14"/>
        <worker name="Helge" gender="male" playerColorIndex="4" playerBodyIndex="4" playerHatIndex="0" playerAccessoryIndex="0" playerHairIndex="2" playerJacketIndex="0" currentSeat="0" position="309.07864379883 38.068710327148 230.03036499023" rotation="-0.040672123432159 -0.054849192500114 -0.99766576290131" vehicleID="17"/>
    </workers>
    <displaySettings>
        <characterName x="0.9828" y="0.93" size="0.010"/>
    </displaySettings>
</ContractorMod>`

So either something in the mod needs to be changed to write that code into the savegame folder xml, or that the reads from the modsettings xml each time you load the game.

**Comment by yumi-modding** [comment]
Thanks. I admit I wrote this piece of code for modhub validation and I might not tested well. I'll fix it.
