### ISSUE TITLE
ContractorMod seems to be incompatible with GuidanceSteering

### ISSUE THREAD

**Issue by asyvan** [yumi-modding/FS17_ContractorMod#60]
It seems there is incompatibility with GuidanceSteering.
No errors, but GuidanceSteering does not work with ContractorMod enabled.

https://github.com/stijnwop/guidanceSteering

**Comment by yumi-modding** [comment]
Hello
I played recently with both mod with no problem. Could you please provide guidanceSteering version (if any, I know mod is not released yet). My version might be outdated.
Yumi

**Comment by asyvan** [comment]
Never mind, when testing again with these two mods only it works fine.
Sorry.
