### ISSUE TITLE
Jeu bloqué dés le lancement de la partie

### ISSUE THREAD

**Issue by Juju-62** [yumi-modding/FS17_ContractorMod#72]
Bonjour yumi,
Depuis quelque jour, j'ai un souci lorsque je lance une partie!
J'ai essayé uniquement avec ton mod ( qui est superbe au passage) et dés que je lance une partie j'ai un problème avec le fichier ContractorMod.lua ligne 1290:

> 2019-09-09 22:09 Error: Running LUA method 'draw'.
> 2019-09-09 22:09 C:/Users/Julien/Documents/My Games/FarmingSimulator2019/mods/FS19_ContractorMod/scripts/ContractorMod.lua:1290: 'for' limit must be a number

du coup cela me génère un autre défaut mais pas important...
Je suis obligé  de quitter le jeu en ouvrant la console... (commande #quit)

Merci de ta futur réponse

**Comment by yumi-modding** [comment]
Hello
Est-ce que ça fait aussi ça sur une nouvelle partie ?
Sinon ce doit être ta sauvegarde qui a un problème.
Si oui, il faut vérifier le fichier ContractorMod.xml dans modSettings, si tu l'as modifié.
Tu peux m'envoyer ces fichiers et ton log complet si tu ne trouves pas.
Yumi

**Comment by Juju-62** [comment]
Oui cela le fait aussi sur une nouvelle partie! 
en effet j'ai modifié le xml mais bien avant je crois...
[ContractorMod.zip](https://github.com/yumi-modding/FS17_ContractorMod/files/3592655/ContractorMod.zip)
Merci pour ta rapide réponse!

**Comment by yumi-modding** [comment]
Hello
Tu pourrais m'envoyer ton log complet et ton dossier savegame stp ? Par mail si tu préfères a yumi at yumi-modding.fr

**Comment by Juju-62** [comment]
Salut!
J'ai remis le fichier `ContractorMod.xml` du zip en lieu et place du mien... J'ai du faire une erreur ou alors c'est mon pc qui cafouille... plus aucun soucis!!!
Par contre je n'arrive pas à leurs faire changer d’apparence... faut-il relancer une partie??
 Merci pour ton aide et bon courage pour la suite!

**Comment by yumi-modding** [comment]
Salut
Ok cool. Si tu veux les changer sur une partie en cours, il te faut modifier le fichier ContractorMod.xml qui est dans ton savegame. Il ressemble beaucoup à celui là.
Si tu veux changer l'apparence pour une nouvelle partie modifie le fichier de modsSettings

**Comment by Juju-62** [comment]
Bizarre, cela ne fonctionne pas chez moi!! pas grave! Merci

**Comment by yumi-modding** [comment]
Ok Recontacte moi si besoin.
Yumi
