### ISSUE TITLE
Game errors on start up

### ISSUE THREAD

**Issue by jonnyyorks** [yumi-modding/FS17_ContractorMod#8]
The game sometimes generates errors after loading when ContractorMod is added for the first time.  Possibly a conflict with Courseplay but I'm not sure
[log error.txt](https://github.com/yumi-modding/FS17_ContractorMod/files/1572862/log.error.txt)

**Comment by yumi-modding** [comment]
Hello

Looks like an initialization problem

> FS17_ContractorMod/scripts/ContractorMod.lua:613: 'for' limit must be a number
> Error: Running LUA method 'update'.

self.numWorkers is not a number.
Could you precise the scenario?
-Start a new game without ContractorMod
-save and them
-load it with ContractorMod
right ?
Thanks

**Comment by jonnyyorks** [comment]
It doesn't happen everytime, this example was it happening when I added the mid into a new game but it also happens when starting a new game with the mod enabled. I'll try and replicate that later

**Comment by jonnyyorks** [comment]
Mod, rather than mid!

**Comment by yumi-modding** [comment]
Thanks :-)
If you're not afraid by traces, for testing only, you can edit ContractorMod.lua file and change debug = false to debug = true at the begining so you'll have traces all the time but this might help to debug.

**Comment by yumi-modding** [comment]
Closing old issue without enough details to analyze.
